{{- if .Values.ingress.enabled -}}
{{- $fullName := include "iqserver.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels: {{ include "iqserver.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostUI }}
      http:
        paths:
          - path: {{ .Values.ingress.hostUIPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: 8070
    - host: {{ .Values.ingress.hostAdmin }}
      http:
        paths:
          - path: {{ .Values.ingress.hostAdminPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: 8071
{{- end }}
