apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      protocol: TCP
      name: nexus-ui
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}
